const reviews = [
  {
    user: "TaylorFan",
    profilePic: "assets/profile1.png",
    artist: "Taylor Swift",
    album: "Red",
    year: 2012,
    review: "Un clásico moderno. Taylor Swift realmente brilla en 'Red'.",
    cover: "assets/album1.png",
    rating: 5,
    likes: "42,633",
    comments: 149
  },
  {
    user: "YeezyFan",
    profilePic: "assets/profile2.png",
    artist: "Kanye West",
    album: "Graduation",
    year: 2007,
    review: "'Graduation' es un álbum icónico que cambió el hip-hop.",
    cover: "assets/album2.png",
    rating: 5,
    likes: "25,477",
    comments: 54
  },
  {
    user: "QueenLover",
    profilePic: "assets/profile3.png",
    artist: "Queen",
    album: "Greatest Hits II",
    year: 1991,
    review: "Una colección increíble de los mejores éxitos de Queen.",
    cover: "assets/album3.png",
    rating: 4,
    likes: "22,855",
    comments: 25
  },
  {
    user: "IndieHead",
    profilePic: "assets/profile4.png",
    artist: "The Strokes",
    album: "Is This It",
    year: 2001,
    review: "El álbum debut que definió el rock de los 2000. Imprescindible.",
    cover: "assets/album4.png",
    rating: 4.5,
    likes: "18,921",
    comments: 33
  },
  {
    user: "PopPrincess",
    profilePic: "assets/profile5.png",
    artist: "Dua Lipa",
    album: "Future Nostalgia",
    year: 2020,
    review: "Un disco pop perfecto de principio a fin. Lleno de energía.",
    cover: "assets/album5.png",
    rating: 5,
    likes: "35,102",
    comments: 89
  },
  {
    user: "Rockero99",
    profilePic: "assets/profile6.png",
    artist: "Led Zeppelin",
    album: "IV",
    year: 1971,
    review: "Stairway to Heaven es una obra maestra. Un álbum legendario.",
    cover: "assets/album6.png",
    rating: 5,
    likes: "50,123",
    comments: 250
  },
  {
    user: "HipHopHead",
    profilePic: "assets/profile7.png",
    artist: "Kendrick Lamar",
    album: "To Pimp a Butterfly",
    year: 2015,
    review: "Una joya del hip-hop moderno. Profundo y complejo.",
    cover: "assets/album7.png",
    rating: 5,
    likes: "45,821",
    comments: 180
  },
  {
    user: "JazzCat",
    profilePic: "assets/profile8.png",
    artist: "Miles Davis",
    album: "Kind of Blue",
    year: 1959,
    review: "El álbum de jazz más importante de la historia. Pura magia.",
    cover: "assets/album8.png",
    rating: 5,
    likes: "30,543",
    comments: 120
  },
  {
    user: "ElectronicFan",
    profilePic: "assets/profile9.png",
    artist: "Daft Punk",
    album: "Discovery",
    year: 2001,
    review: "Un viaje sonoro increíble. One More Time es un himno.",
    cover: "assets/album9.png",
    rating: 4.5,
    likes: "38,987",
    comments: 150
  },
  {
    user: "ReggaeVibes",
    profilePic: "assets/profile10.png",
    artist: "Bob Marley",
    album: "Exodus",
    year: 1977,
    review: "Un mensaje de paz y unidad. La esencia del reggae.",
    cover: "assets/album10.png",
    rating: 5,
    likes: "42,111",
    comments: 130
  },
  {
    user: "GrungeGirl",
    profilePic: "assets/profile11.png",
    artist: "Nirvana",
    album: "Nevermind",
    year: 1991,
    review: "El disco que cambió el rock. Smells Like Teen Spirit es un himno.",
    cover: "assets/album11.png",
    rating: 5,
    likes: "48,321",
    comments: 200
  },
  {
    user: "SoulSister",
    profilePic: "assets/profile12.png",
    artist: "Amy Winehouse",
    album: "Back to Black",
    year: 2006,
    review: "Una voz única. Un álbum lleno de alma y dolor.",
    cover: "assets/album12.png",
    rating: 5,
    likes: "40,543",
    comments: 160
  },
  {
    user: "Metalhead",
    profilePic: "assets/profile13.png",
    artist: "Metallica",
    album: "Master of Puppets",
    year: 1986,
    review: "Una obra maestra del metal. Riffs inolvidables.",
    cover: "assets/album13.png",
    rating: 5,
    likes: "46,876",
    comments: 220
  },
  {
    user: "PopFanatic",
    profilePic: "assets/profile14.png",
    artist: "Michael Jackson",
    album: "Thriller",
    year: 1982,
    review: "El rey del pop en su máxima expresión. Un clásico.",
    cover: "assets/album14.png",
    rating: 5,
    likes: "55,432",
    comments: 300
  },
  {
    user: "AlternativeRock",
    profilePic: "assets/profile15.png",
    artist: "Radiohead",
    album: "OK Computer",
    year: 1997,
    review: "Una obra de arte. Un álbum que te vuela la cabeza.",
    cover: "assets/album15.png",
    rating: 5,
    likes: "49,876",
    comments: 250
  },
  {
    user: "ClassicRockFan",
    profilePic: "assets/profile16.png",
    artist: "The Beatles",
    album: "Abbey Road",
    year: 1969,
    review: "Una joya de principio a fin. La despedida de una leyenda.",
    cover: "assets/album16.png",
    rating: 5,
    likes: "52,345",
    comments: 280
  },
  {
    user: "RnbLover",
    profilePic: "assets/profile17.png",
    artist: "Frank Ocean",
    album: "Blonde",
    year: 2016,
    review: "Un álbum introspectivo y hermoso. Una obra de arte.",
    cover: "assets/album17.png",
    rating: 5,
    likes: "43,876",
    comments: 190
  },
  {
    user: "FolkFan",
    profilePic: "assets/profile18.png",
    artist: "Bob Dylan",
    album: "Highway 61 Revisited",
    year: 1965,
    review: "Un poeta con una guitarra. Un álbum que cambió la música.",
    cover: "assets/album18.png",
    rating: 5,
    likes: "36,876",
    comments: 170
  },
  {
    user: "PunkRock",
    profilePic: "assets/profile19.png",
    artist: "The Ramones",
    album: "Ramones",
    year: 1976,
    review: "Pura energía. El nacimiento del punk rock.",
    cover: "assets/album19.png",
    rating: 4.5,
    likes: "33,876",
    comments: 140
  },
  {
    user: "DiscoQueen",
    profilePic: "assets/profile20.png",
    artist: "Bee Gees",
    album: "Saturday Night Fever",
    year: 1977,
    review: "La banda sonora de una época. Pura fiebre disco.",
    cover: "assets/album20.png",
    rating: 4.5,
    likes: "39,876",
    comments: 160
  }
];
